#!/bin/bash

D_R=`cd \`dirname $0\` ; pwd -P`
source $D_R/shell_aliases.d/run_commands.sh || exit $?

run_commands \
  set_language_to_english \
  trackpad_unnatural_scroll_direction \
  dock_autohide_on \
  dock_only_show_active_apps \
  dock_restart \
  menubar_autohide_on \
  menubar_clock_with_date \
  menubar_show_battery_percent \
  menubar_extras_bluetooth \
  guest_account_disable \
  ui_server_restart \
  diasble_bluetooth_hid_autoseek \
  install_homebrew \
  disable_homebrew_analytics \
  install_homebrew_caskroom \
  install_mas \
  mas_signin \
  install_coreutils \
  install_screen \
  install_hub \
  install_parallel \
  install_git \
  install_caffeine \
  install_commandq \
  install_1password \
  install_git_secrets \
  install_pwgen \
  install_tunnelblick \
  install_spotify \
  install_airfoil \
  install_omnifocus \
  install_iterm \
  install_openssh \
  install_rsync \
  install_macvim \
  install_atom \
  install_janus \
  install_shellcheck \
  install_google_chrome_1password_support \
  install_google_chrome \
  install_firefox \
  install_grammarly \
  install_tor \
  install_torsocks \
  install_dante \
  install_torbrowser \
  install_youtube_dl \
  install_ffmpeg \
  install_lastpass \
  install_alfred \
  install_slack \
  install_zoomus \
  install_whatsapp \
  install_skype \
  install_terminal_notifier \
  install_rubbernet \
  install_wifi_explorer \
  install_pages \
  install_numbers \
  install_keynote \
  install_pixelmator \
  install_daisy_disk \
  install_disk_drill_media_recovery \
  install_mactracker \
  install_steam \
  install_audio_hijack \
  install_hammerspoon \
  install_hazel \
  install_shell_aliases \
  install_zsh \
  install_rbenv \
  install_rbenv_ruby \
  install_dotfiles \
  install_wget \
  install_axel \
  install_rg \
  install_ag \
  install_rpl \
  install_java \
  install_htop \
  install_pstree \
  install_p7zip \
  install_aria2 \
  install_libreoffice \
  install_font_microsoft \
  install_logic_pro_x \
  install_quik \
  autostart_mail \
  autostart_calendar \
  sync_github_repositories \
  update_system \
  || return $?

run_upgrades \
  git \
  screen \
  openssl \
  openssh \
  rsync \
  tor \
  torsocks \
  dante \
  youtube-dl \
  ffmpeg \
  zsh \
  wget \
  aria2 \

