#!/bin/bash

D_R=`cd \`dirname $0\` ; pwd -P`
source $D_R/shell_aliases.d/run_commands.sh || exit $?

run_commands \
  trackpad_unnatural_scroll_direction \
  dock_autohide_on \
  dock_restart \
  menubar_autohide_on \
  ui_server_restart \
  install_homebrew \
  disable_homebrew_analytics \
  install_mas \
  mas_signin \
  install_caffeine \
  install_1password \
  install_git_secrets \
  install_pwgen \
  install_tunnelblick \
  install_spotify \
  install_airfoil \
  install_omnifocus \
  install_iterm \
  install_macvim \
  install_janus \
  install_shellcheck \
  install_google_chrome \
  install_firefox \
  install_grammarly \
  install_tor \
  install_torsocks \
  install_dante \
  install_torbrowser \
  install_youtube_dl \
  install_lastpass \
  install_alfred \
  install_slack \
  install_zoomus \
  install_skype \
  install_terminal_notifier \
  install_rubbernet \
  install_wifi_explorer \
  install_pages \
  install_numbers \
  install_keynote \
  install_pixelmator \
  install_daisy_disk \
  install_disk_drill_media_recovery \
  install_mactracker \
  install_steam \
  install_audio_hijack \
  install_hammerspoon \
  install_shell_aliases \
  install_zsh \
  install_rbenv \
  install_dotfiles \
  install_wget \
  install_rg \
  install_ag \
  install_java \
  install_htop \
  install_pstree \
  install_p7zip \
  install_libreoffice \
  install_font_microsoft \
  sync_github_repositories \
  update_system \
  || return $?
